Install-WindowsFeature -Name BitLocker
Install-WindowsFeature -Name EnhancedStorage
Install-WindowsFeature -Name FileAndStorage-Services
Install-WindowsFeature -Name NET-Framework-45-ASPNET
Install-WindowsFeature -Name NET-Framework-45-Core
Install-WindowsFeature -Name NET-Framework-45-Features
Install-WindowsFeature -Name NET-Framework-Core
Install-WindowsFeature -Name NET-Framework-Features
Install-WindowsFeature -Name NET-HTTP-Activation
Install-WindowsFeature -Name NET-WCF-HTTP-Activation45
Install-WindowsFeature -Name NET-WCF-Services45
Install-WindowsFeature -Name NET-WCF-TCP-PortSharing45
Install-WindowsFeature -Name PowerShell
Install-WindowsFeature -Name PowerShellRoot
Install-WindowsFeature -Name PowerShell-V2
Install-WindowsFeature -Name Storage-Services
Install-WindowsFeature -Name System-DataArchiver
Install-WindowsFeature -Name Telnet-Client
Install-WindowsFeature -Name WAS
Install-WindowsFeature -Name WAS-Config-APIs
Install-WindowsFeature -Name WAS-NET-Environment
Install-WindowsFeature -Name WAS-Process-Model
Install-WindowsFeature -Name Web-App-Dev
Install-WindowsFeature -Name Web-Asp-Net45
Install-WindowsFeature -Name Web-Basic-Auth
Install-WindowsFeature -Name Web-Cert-Auth
Install-WindowsFeature -Name Web-Client-Auth
Install-WindowsFeature -Name Web-Common-Http
Install-WindowsFeature -Name Web-Default-Doc
Install-WindowsFeature -Name Web-Digest-Auth
Install-WindowsFeature -Name Web-Dir-Browsing
Install-WindowsFeature -Name Web-Dyn-Compression
Install-WindowsFeature -Name Web-Filtering
Install-WindowsFeature -Name Web-Health
Install-WindowsFeature -Name Web-Http-Errors
Install-WindowsFeature -Name Web-Http-Logging
Install-WindowsFeature -Name Web-Http-Redirect
Install-WindowsFeature -Name Web-Http-Tracing
Install-WindowsFeature -Name Web-IP-Security
Install-WindowsFeature -Name Web-ISAPI-Ext
Install-WindowsFeature -Name Web-ISAPI-Filter
Install-WindowsFeature -Name Web-Log-Libraries
Install-WindowsFeature -Name Web-Mgmt-Console
Install-WindowsFeature -Name Web-Mgmt-Tools
Install-WindowsFeature -Name Web-Net-Ext
Install-WindowsFeature -Name Web-Net-Ext45
Install-WindowsFeature -Name Web-Performance
Install-WindowsFeature -Name Web-Request-Monitor
Install-WindowsFeature -Name Web-Scripting-Tools
Install-WindowsFeature -Name Web-Security
Install-WindowsFeature -Name Web-Server
Install-WindowsFeature -Name Web-Stat-Compression
Install-WindowsFeature -Name Web-Static-Content
Install-WindowsFeature -Name Web-Url-Auth
Install-WindowsFeature -Name Web-WebServer
Install-WindowsFeature -Name Web-Windows-Auth
Install-WindowsFeature -Name Windows-Defender
Install-WindowsFeature -Name WoW64-Support
Install-WindowsFeature -Name XPS-Viewer
